### PR TITLE
Updated ED2 references to be Static (Fixes Crash)

### PR DESCRIPTION
**Pull request by ElenaiDev**

### CODE REVIEW

**Comment by Corvus20** [comment]
Well Tfarcenim straight up disappeared, didn't they?

**Comment by Tfarcenim** [comment]
> Well Tfarcenim straight up disappeared, didn't they?

Ah yes, being busy with irl and paid work is called "disappearing" now.  I'm not gone, I'm just focusing on stuff that pays the bills and keeps me from living on the street or worse.  This will be visited when I have free time, but I don't know when that will be.

**Comment by Corvus20** [comment]
> > Well Tfarcenim straight up disappeared, didn't they?
> 
> Ah yes, being busy with irl and paid work is called "disappearing" now. I'm not gone, I'm just focusing on stuff that pays the bills and keeps me from living on the street or worse. This will be visited when I have free time, but I don't know when that will be.

That was an ignorant thing for me to say, I apologize.

**Comment by Shibva** [comment]
I wonder when this will merge, its been a long time now, I understand the dev is busy and all. just hope this gets merged so Etheni Dodge 2 can be useable

**Comment by Shibva** [comment]
it seems that he/she active, maybe they have just forgotten about this issue or something awaiting a pending pull

**Comment by Tfarcenim** [comment]
Merged, but there will not be any builds until 1.18 is ready.

**Comment by Shibva** [comment]
. . .  THANK YOU GOD! MY PRAYERS HAVE BEEN HEARD!

**Pull request merged**
